"""Training loop for link prediction on the Nostr follow graph.

Task: directed personalized link scoring.
Positives are follow/trust edges. Mute edges are explicit negative
supervision. Random negatives are generated by LinkNeighborLoader.
"""

import logging
import os

import torch
import torch.nn as nn
import torch.nn.functional as F
import trackio
from torch_geometric.loader import LinkNeighborLoader

logger = logging.getLogger(__name__)
PROGRESS_LOG_EVERY = 100


def train(
    module: nn.Module,
    loader: LinkNeighborLoader,
    train_epochs: int = 1,
    lr: float = 1e-3,
    output_dir: str = "",
    device: torch.device = torch.device("cpu"),
):
    module = module.to(device)
    optimizer = torch.optim.Adam(module.parameters(), lr=lr)
    num_batches_total = len(loader)

    global_step = 0

    for epoch in range(train_epochs):
        module.train()
        total_loss = 0.0
        num_batches = 0

        for batch_idx, batch in enumerate(loader, start=1):
            batch = batch.to(device)
            optimizer.zero_grad()

            embeddings = module(batch.x, batch.edge_index)

            src = embeddings[batch.edge_label_index[0]]
            dst = embeddings[batch.edge_label_index[1]]
            scores = (src * dst).sum(dim=1)
            labels = (batch.edge_label > 0).float()

            loss = F.binary_cross_entropy_with_logits(scores, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            num_batches += 1
            global_step += 1

            if batch_idx == 1 or batch_idx % PROGRESS_LOG_EVERY == 0:
                logger.info(
                    "Epoch %s/%s Batch %s/%s loss=%.4f nodes=%s edges=%s",
                    epoch + 1,
                    train_epochs,
                    batch_idx,
                    num_batches_total,
                    loss.item(),
                    batch.num_nodes,
                    batch.edge_index.size(1),
                )

            if global_step % 80 == 0:
                trackio.log(
                    {
                        "train/loss_step": loss.item(),
                        "train/step": global_step,
                    }
                )

        avg_loss = total_loss / max(num_batches, 1)
        trackio.log(
            {
                "train/loss_epoch": avg_loss,
                "train/epoch": epoch + 1,
            }
        )
        logger.info(
            "Epoch %s/%s loss=%.4f",
            epoch + 1,
            train_epochs,
            avg_loss,
        )

    save_model(module, output_dir)


def save_model(module: nn.Module, output_dir: str):
    os.makedirs(output_dir, exist_ok=True)
    torch.save(module.state_dict(), os.path.join(output_dir, "model.pt"))
    logger.info("Saved model to %s/model.pt", output_dir)
